name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish WordPress
        run: |
          ./gradlew wordPressUpload -Pwordpress-host="neo4j.com" -Pwordpress-username="${WORDPRESS_USER}" -Pwordpress-password="${WORDPRESS_PASSWORD}" -Pstage=production
        env:
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      - name: Publish Zendesk
        run: |
          ./gradlew zenDeskUpload -Pzendesk-email="${ZENDESK_EMAIL}" -Pzendesk-host="support.neo4j.com" -Pzendesk-apitoken="${ZENDESK_APITOKEN}" -Pstage=production
        env:
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_APITOKEN: ${{ secrets.ZENDESK_APITOKEN }}
